apps/weather/urls.py
from django.urls import path

# from apps.weather import views
from apps.weather.views import Home

app_name = "weather"

urlpatterns = [
    path("", Home.as_view(), name="home"),
]

weather_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("apps.weather.urls", namespace="weather")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/weather/models.py
from django.db import models

# Create your models here.

apps/weather/views.py
import re

from django.conf import settings
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from django.views.generic import TemplateView

from apps.weather.helpers import weather_data


class Home(TemplateView):
    """
    View for App Store AppHome
    """

    template_name = "index.html"
    context_object_name = "data"

    @method_decorator(cache_page(settings.CUSTOM_CACHE_SECONDS))
    def get(self, request, *args, **kwargs):
        query_params = self.request.GET

        city = query_params.get("city", "Berlin")

        data = None
        if city:
            city = re.sub("\s+", " ", city).strip()

            # Fetch weather data from openweathermap API
            data = weather_data(city)

        context = self.get_context_data(**kwargs)
        context["data"] = data
        return self.render_to_response(context)

apps/weather/templates/index.html
{% extends 'base.html'%}
{% load i18n %}

{% block title %}| {{ data.city }}, {{ data.country }} | {% translate "Weather" %}{% endblock title %}

{% block content %}
<main class="container">
    <div class="clearfix">&nbsp;</div><br><br>
    <div class="container">
        <div class="col-md-6 offset-md-3 text-center">
            <div class="d-flex align-items-center">
                <form class="w-100" action="{% url 'weather:home' %}" method="get">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="city" value="{{request.GET.city.strip}}"
                               placeholder="{% translate 'Search city' %}" aria-label="{% translate 'Search' %}"
                               autocomplete="off">
                        <button type="submit" class="btn btn-primary">{% translate 'Search' %}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="clearfix">&nbsp;</div>
        <div class="col-md-6 offset-md-3 text-center">
            {% if data %}
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col-md-4 p-4 d-flex flex-column d-lg-block">
                    <img src="https://openweathermap.org/img/wn/{{ data.icon }}@2x.png"
                         alt="{{ data.weather.0.main }}" width="100px">
                    <strong>{{ data.temperature.temp}}°C</strong>
                    <p><strong>{{ data.main }}</strong></p>
                    <p>{{ data.description }}</p>

                </div>
                <div class="col p-4 d-flex flex-column position-static" style="text-align: left; font-size: 14px;">
                    <h6>{% translate "City" %}</h6>
                    <p>{{ data.city }}, {{ data.country }}</p>
                    <div class="row g-4">
                        <div class="col-md-6">
                            <h6>{% translate "Temperature" %}</h6>
                            <p>
                                <b>{% translate "Low" %}:</b> {{ data.temperature.min }}°C, <b>{% translate "High" %}:</b> {{ data.temperature.max }}°C
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h6>{% translate "Wind" %}</h6>
                            <p>{{ data.wind.speed }} m/s {{ data.wind.direction }}</p>
                        </div>
                    </div>

                    <div class="row g-4">
                        <div class="col-md-6">
                            <h6>{% translate "Humidity" %}</h6>
                            <p>{{ data.humidity }}%</p>
                        </div>

                        <div class="col-md-6">
                            <h6>{% translate "Pressure" %}</h6>
                            <p>{{ data.pressure }} hPa</p>
                        </div>
                    </div>
                </div>
            </div>
            {%else%}
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="clearfix">&nbsp;</div>
                <span width="100px">
                    <svg xmlns="http://www.w3.org/2000/svg" id="bac3cfc7-b61b-48ce-8441-8100e40ddaa6"
                         data-name="Layer 1" width="150px" viewBox="0 0 797.5 834.5"
                         class="injected-svg ClassicGrid__ImageFile-sc-td9pmq-4 fNAcXv grid_media"
                         xmlns:xlink="http://www.w3.org/1999/xlink"><title>void</title><ellipse cx="308.5" cy="780"
                                                                                                rx="308.5" ry="54.5"
                                                                                                fill="#3f3d56"></ellipse><circle
                            cx="496" cy="301.5" r="301.5" fill="#3f3d56"></circle><circle cx="496" cy="301.5"
                                                                                          r="248.89787"
                                                                                          opacity="0.05"></circle><circle
                            cx="496" cy="301.5" r="203.99362" opacity="0.05"></circle><circle cx="496" cy="301.5"
                                                                                              r="146.25957"
                                                                                              opacity="0.05"></circle><path
                            d="M398.42029,361.23224s-23.70394,66.72221-13.16886,90.42615,27.21564,46.52995,27.21564,46.52995S406.3216,365.62186,398.42029,361.23224Z"
                            transform="translate(-201.25 -32.75)" fill="#d0cde1"></path><path
                            d="M398.42029,361.23224s-23.70394,66.72221-13.16886,90.42615,27.21564,46.52995,27.21564,46.52995S406.3216,365.62186,398.42029,361.23224Z"
                            transform="translate(-201.25 -32.75)" opacity="0.1"></path><path
                            d="M415.10084,515.74682s-1.75585,16.68055-2.63377,17.55847.87792,2.63377,0,5.26754-1.75585,6.14547,0,7.02339-9.65716,78.13521-9.65716,78.13521-28.09356,36.8728-16.68055,94.81576l3.51169,58.82089s27.21564,1.75585,27.21564-7.90132c0,0-1.75585-11.413-1.75585-16.68055s4.38962-5.26754,1.75585-7.90131-2.63377-4.38962-2.63377-4.38962,4.38961-3.51169,3.51169-4.38962,7.90131-63.2105,7.90131-63.2105,9.65716-9.65716,9.65716-14.92471v-5.26754s4.38962-11.413,4.38962-12.29093,23.70394-54.43127,23.70394-54.43127l9.65716,38.62864,10.53509,55.3092s5.26754,50.04165,15.80262,69.356c0,0,18.4364,63.21051,18.4364,61.45466s30.72733-6.14547,29.84941-14.04678-18.4364-118.5197-18.4364-118.5197L533.62054,513.991Z"
                            transform="translate(-201.25 -32.75)" fill="#2f2e41"></path><path
                            d="M391.3969,772.97846s-23.70394,46.53-7.90131,48.2858,21.94809,1.75585,28.97148-5.26754c3.83968-3.83968,11.61528-8.99134,17.87566-12.87285a23.117,23.117,0,0,0,10.96893-21.98175c-.463-4.29531-2.06792-7.83444-6.01858-8.16366-10.53508-.87792-22.826-10.53508-22.826-10.53508Z"
                            transform="translate(-201.25 -32.75)" fill="#2f2e41"></path><path
                            d="M522.20753,807.21748s-23.70394,46.53-7.90131,48.28581,21.94809,1.75584,28.97148-5.26754c3.83968-3.83969,11.61528-8.99134,17.87566-12.87285a23.117,23.117,0,0,0,10.96893-21.98175c-.463-4.29531-2.06792-7.83444-6.01857-8.16367-10.53509-.87792-22.826-10.53508-22.826-10.53508Z"
                            transform="translate(-201.25 -32.75)" fill="#2f2e41"></path><circle cx="295.90488"
                                                                                                cy="215.43252"
                                                                                                r="36.90462"
                                                                                                fill="#ffb8b8"></circle><path
                            d="M473.43048,260.30832S447.07,308.81154,444.9612,308.81154,492.41,324.62781,492.41,324.62781s13.70743-46.39439,15.81626-50.61206Z"
                            transform="translate(-201.25 -32.75)" fill="#ffb8b8"></path><path
                            d="M513.86726,313.3854s-52.67543-28.97148-57.943-28.09356-61.45466,50.04166-60.57673,70.2339,7.90131,53.55335,7.90131,53.55335,2.63377,93.05991,7.90131,93.93783-.87792,16.68055.87793,16.68055,122.90931,0,123.78724-2.63377S513.86726,313.3854,513.86726,313.3854Z"
                            transform="translate(-201.25 -32.75)" fill="#d0cde1"></path><path
                            d="M543.2777,521.89228s16.68055,50.91958,2.63377,49.16373-20.19224-43.89619-20.19224-43.89619Z"
                            transform="translate(-201.25 -32.75)" fill="#ffb8b8"></path><path
                            d="M498.50359,310.31267s-32.48318,7.02339-27.21563,50.91957,14.9247,87.79237,14.9247,87.79237l32.48318,71.11182,3.51169,13.16886,23.70394-6.14547L528.353,425.32067s-6.14547-108.86253-14.04678-112.37423A33.99966,33.99966,0,0,0,498.50359,310.31267Z"
                            transform="translate(-201.25 -32.75)" fill="#d0cde1"></path><polygon
                            points="277.5 414.958 317.885 486.947 283.86 411.09 277.5 414.958" opacity="0.1"></polygon><path
                            d="M533.896,237.31585l.122-2.82012,5.6101,1.39632a6.26971,6.26971,0,0,0-2.5138-4.61513l5.97581-.33413a64.47667,64.47667,0,0,0-43.1245-26.65136c-12.92583-1.87346-27.31837.83756-36.182,10.43045-4.29926,4.653-7.00067,10.57018-8.92232,16.60685-3.53926,11.11821-4.26038,24.3719,3.11964,33.40938,7.5006,9.18513,20.602,10.98439,32.40592,12.12114,4.15328.4,8.50581.77216,12.35457-.83928a29.721,29.721,0,0,0-1.6539-13.03688,8.68665,8.68665,0,0,1-.87879-4.15246c.5247-3.51164,5.20884-4.39635,8.72762-3.9219s7.74984,1.20031,10.062-1.49432c1.59261-1.85609,1.49867-4.559,1.70967-6.99575C521.28248,239.785,533.83587,238.70653,533.896,237.31585Z"
                            transform="translate(-201.25 -32.75)" fill="#2f2e41"></path><circle cx="559" cy="744.5"
                                                                                                r="43"
                                                                                                fill="#adadad"></circle><circle
                            cx="54" cy="729.5" r="43" fill="#adadad"></circle><circle cx="54" cy="672.5" r="31"
                                                                                      fill="#adadad"></circle><circle
                            cx="54" cy="624.5" r="22" fill="#adadad"></circle></svg>
                </span>
                <div class="clearfix">&nbsp;</div>
                <p>{% translate "No data" %} "{{request.GET.city.strip}}"</p>
            </div>
            {% endif %}
        </div>
    </div>
</main>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n static %}

<!-- Head -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Weather App {% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom style CSS -->
    <style>
        .c {
            text-align: center;
            display: block;
            position: relative;
            width: 80%;
            margin: 100px auto;
        }

        ._ERROR {
            font-size: 90px;
            position: relative;
            display: inline-block;
            z-index: 2;
            height: 115px;
            letter-spacing: 15px;
        }

        ._1 {
            text-align: center;
            display: block;
            position: relative;
            letter-spacing: 12px;
            font-size: 2em;
            height: 80px;
        }

        .text {
            font-size: 70px;
            text-align: center;
            position: relative;
            display: inline-block;
            margin: 19px 0px 0px 0px;
            z-index: 3;
            width: 100%;
            line-height: 1.2em;
            display: inline-block;
        }

        hr {
            padding: 0;
            border: none;
            border-top: 5px solid #fff;
            color: #fff;
            text-align: center;
            margin: 0px auto;
            width: 420px;
            height: 10px;
            z-index: -10;
        }

        footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 60px;
        }

        @media (max-width: 768px) {
            footer {
                position: relative;
            }
        }
    </style>

</head>
<!-- End Head -->

<!-- Body -->
<body>

<!-- Navigation -->
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'weather:home' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     width="24px" height="24px" viewBox="0 0 64 64" xml:space="preserve">
                    <path fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10"
                          d="M56,45c4.19,0,7-2.81,7-7c0-4.189-2.81-9-7-9  c0-10.475-9.525-18-20-18c-9.271,0-17.348,6.211-19,15c0,0-1.232,0-2,0c-5.238,0-9,4.762-9,10s3.762,9,9,9H56z"></path>
                    <path fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10"
                          d="M29.999,11.752C27.793,10.028,25.017,9,22,9  C14.82,9,9,14.82,9,22c0,2.577,0.707,3.979,2,6"></path>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="6" y1="22" x2="0"
                          y2="22"></line>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="22" y1="6" x2="22"
                          y2="0"></line>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="10" y1="10" x2="4"
                          y2="4"></line>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="20" y1="48" x2="12"
                          y2="62"></line>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="30" y1="48" x2="22"
                          y2="62"></line>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="40" y1="48" x2="32"
                          y2="62"></line>
                    <line fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" x1="50" y1="48" x2="42"
                          y2="62"></line>
                </svg>
                <strong>Weather App</strong></a>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"></ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input name="next" type="hidden" value="{{ request.get_full_path }}"/>
                <select class="form-select" name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                        {% translate language.name %} ({{ language.code }})
                    </option>
                    {% endfor %}
                </select>
                    <button type="submit" class="btn btn-secondary">{% translate 'Change' %}</button>
                </div>
            </form>
        </div>
    </div>
</header>
<!-- End Navigation -->

<!-- Page Content -->
<div class="container">

    {% if apps|length > 0 and request.GET.q %}
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body">
            <p class="text-white m-0">
                Search result found for keyword " {{ request.GET.q.strip }} "
            </p>
        </div>
    </div>
    {% endif %}

    {% block content %}{% endblock content %}

</div>
<!-- End Page Content -->

<!-- Footer -->
<footer class="text-muted py-5 bg-dark">
    <div class="container">
        <p class="float-end">
            <a class="text-white" href="#">{% translate "Back to top" %}</a>
        </p>
        <p class="text-white">{% translate "Copyright" %} &copy; Weather App - 2022</p>
    </div>
</footer>
<!-- End Footer -->

<!-- Bootstrap core JavaScript -->
<script src="https://getbootstrap.com/docs/5.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
{% block script %}{% endblock script %}

</body>
<!-- End Body -->

</html>